acf-json/group_5d5ef70bd03ce.json
js/filter.js
sass/forms/_fields.scss
template-parts/content-degrees.php
template-parts/content-links.php
template-parts/filter-labs.php
template-parts/filter-programs.php
template-parts/filter-resgroups.php
template-parts/filter-studentopportunities.php
template-parts/filter-studentsupport.php

Reworking filters on Degrees page. Improvements here will  be worked into other filters. This is linked to issue #10 #7 #8 #9

working on reworking the filters. This is a utility commit

---

archive.php
functions.php
header-archive.php
home.php
template-parts/content-archive.php

Developed rudimentary post archive template. Good for categories and posts.

post archive

---

acf-json/group_5b79d00c916fb.json
acf-json/group_5ced7f580f5aa.json
acf-json/group_5d5ef70bd03ce.json
functions.php
js/filter.js
page.php
sass/site/custom/_custom.scss
sass/site/custom/_programs.scss
template-parts/content-links.php
template-parts/filter-support.php

Going to merge this and create a new branch for working on stuff. This branch was poorly named anyway, as it should've been more specific.

Launch countdown

---

footer.php
functions.php
js/back-to-top.js
sass/navigation/_links.scss
sass/site/custom/_custom.scss
template-parts/to-top.php

Back to top

---

acf-json/group_5c5378f0b7938.json
front-page.php
functions.php
sass/layout/_no-sidebar.scss
sass/site/custom/_custom.scss
synctheme

Homepage changes

---

header.php

adjusting captions for header featured images.

fixing captions for the header

---

sass/site/custom/_custom.scss
sass/site/custom/_news.scss

Knocking off a few of the "low hanging fruit" issues. See commit messages.

Low hangers

---

sass/forms/_buttons.scss
sass/site/custom/_custom.scss
sass/site/custom/_news.scss
template-parts/footer-cta.php

Made button on CTA consistent with button on News page. Closes:#76

Button fix

---

sass/site/primary/_archive.scss
template-parts/content-search.php

Search fiddling

---

sass/site/primary/_archive.scss
sass/site/primary/_posts-and-pages.scss
template-parts/content-search.php

Off site link posts were showing up as posts to the site in both internal search results and Google SERPs, as described in #78 I believe this fixes it.

Search work

---

sass/modules/_alignments.scss

fixing image alignments per #63

---

acf-json/group_5c5378f0b7938.json
acf-json/group_5cfad2654c40c.json
template-parts/content-page.php

per Issue #77. See comment in that issue for explanation.

re-working and standardizing FontAwesome Icons

---

sass/layout/_grid.scss

adjusting image widths

---

js/majors-front.js
template-parts/content-degree.php

Issue work

---

functions.php
sass/navigation/_links.scss

adjusted single template for CPTs to add padding to featured image at the top of the template.

fixing style issues

---

functions.php

fixed social sharing function reddit link

---

acf-json/group_5c5378f0b7938.json
functions.php
header-home.php
page.php
template-parts/content-page.php

Hero slider -- Fix ACF repeater update

---

js/filter.js
sass/layout/_panels.scss

Some issues

---

functions.php

Applying the same cache busting approach to all obvious custom styles and scripts enqueued in functions.php

More cache busting for more styles and scripts

---

js/filters.js
sass/style.scss
template-parts/filterable-content-query.php

* Cache busting by increasing theme verison number
* Filter reset search clear fix
* Sorting "lab" post type by last_name meta value

Some minor fixes for filter pages and cache busting

---

acf-json/group_5a304e6aabaa6.json
functions.php
js/filters.js
js/navigation2.js
package-lock.json
package.json
sass/navigation/_breadcrumbs.scss
sass/navigation/_menus.scss
sass/site/custom/_alert-bar.scss
sass/style.scss
template-filterable-content.php
template-parts/alert-bar.php
template-unit-listings.php

These are changes that have been made to the theme in campuspress, but never copied back into this project.

capturing changes that have been made to the theme in campuspress
